## Panda Data Structures

In [2]:
import numpy as np

In [2]:
ar1 = np.array([0,4,1,2,3])
ar1

array([0, 4, 1, 2, 3])

In [3]:

ar1.cumsum()


array([ 0,  4,  5,  7, 10], dtype=int32)

### 2D- Array Creation

In [4]:
ar2 = np.array([range(5),range(5)]) #2-D Array
ar2

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

### Shape or no of row and columns in array

In [5]:
print(("Row","Col"))
print(ar2.shape)


('Row', 'Col')
(2, 5)


### Dimension of Array

In [6]:
ar2.ndim

2

### Range of value of n size or from n1 to n2 spaced at a distance

In [7]:
ar3 = np.arange(12)
ar3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [8]:
ar4 = np.arange(3,40,3)
ar4

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39])

### Linear Spaced 20 values from 0 to 1

In [9]:
ar5 = np.linspace(0,3.0/3,20) 
ar5

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

### Random Array

In [10]:
np.random.seed()
rnad = abs(np.random.randn(20)*100)
rnad

array([ 92.95425488,  73.70451323,  28.69354844,  14.8039133 ,
        34.68537293,  97.14371973,  17.44223479,  56.42906153,
        95.87968366, 183.95154111, 124.23502657,  21.11960408,
        61.41597594,  46.17370041,  21.51293672,  86.22793143,
       280.57487503,  23.96324315,  92.42555419,  21.19441315])

### Numpy Ones Matrix of any dimension

In [11]:
ar6 = np.ones((5,1,4))
ar6.shape
ar6

array([[[1., 1., 1., 1.]],

       [[1., 1., 1., 1.]],

       [[1., 1., 1., 1.]],

       [[1., 1., 1., 1.]],

       [[1., 1., 1., 1.]]])

### Zeros Array

In [12]:
ar8 = np.zeros((4,2))
ar8

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

### Identity Array

In [13]:
ar9 = np.eye(4)
ar9

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### Diagonal array

In [14]:
ar10 = np.diag((2,1,4,6))
ar10

array([[2, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 4, 0],
       [0, 0, 0, 6]])

### Random array

In [15]:
ar11 = np.random.rand(3)
ar11

array([0.34182023, 0.28134786, 0.69962996])

### Uninitialized Array or Empty Error

In [16]:
ar13 = np.empty((3,6))
ar13

array([[0.e+000, 0.e+000, 0.e+000, 0.e+000, 0.e+000, 0.e+000],
       [0.e+000, 0.e+000, 0.e+000, 0.e+000, 0.e+000, 5.e-324],
       [0.e+000, 0.e+000, 0.e+000, 0.e+000, 0.e+000, 0.e+000]])

### Tiling big array from smalller array

#### Horizontal tiling

In [17]:
np.tile(np.array([[1,2],[6,7]]),(5))  

array([[1, 2, 1, 2, 1, 2, 1, 2, 1, 2],
       [6, 7, 6, 7, 6, 7, 6, 7, 6, 7]])

#### Array like Tiling

In [18]:
np.tile(np.array([[1,2],[6,7]]),(2,4)) 

array([[1, 2, 1, 2, 1, 2, 1, 2],
       [6, 7, 6, 7, 6, 7, 6, 7],
       [1, 2, 1, 2, 1, 2, 1, 2],
       [6, 7, 6, 7, 6, 7, 6, 7]])

### Datatype of content defining and finding

In [19]:
ar = np.array([2,-1,6,3.34],dtype ='float')
ar

array([ 2.  , -1.  ,  6.  ,  3.34])

In [20]:
ar.dtype

dtype('float64')

In [21]:
ar = np.array([2,-1,6,3])
ar.dtype

dtype('int32')

In [22]:
ar = np.array([2,-1,6,3.34])
ar.dtype

dtype('float64')

In [23]:
sar = np.array(['Goodbye','Welcome','Tata','Goodnight'])
sar

array(['Goodbye', 'Welcome', 'Tata', 'Goodnight'], dtype='<U9')

In [24]:
sar.dtype


dtype('<U9')

In [25]:
sar.astype('S9')

array([b'Goodbye', b'Welcome', b'Tata', b'Goodnight'], dtype='|S9')

### Numpy indexing Slicing

In [26]:
ar = np.arange(5)
print(ar)
print('First Element {}. Last Element {}'.format(ar[0],ar[-1]))


[0 1 2 3 4]
First Element 0. Last Element 4


#### Reverse Order Array

In [27]:
ar[::-1]

array([4, 3, 2, 1, 0])

#### Multidimensional Array Slicing

In [28]:
ar = np.array([[2,3,4],[9,8,7],[11,12,13]])
ar

array([[ 2,  3,  4],
       [ 9,  8,  7],
       [11, 12, 13]])

### Multidimensional Array indexed

In [29]:
ar[1,0]


9

#### Set the entry at row and column 

In [30]:
ar[1,1:]=5
ar

array([[ 2,  3,  4],
       [ 9,  5,  5],
       [11, 12, 13]])

In [31]:
  ar[2] # Retrieve Row

array([11, 12, 13])

In [32]:
ar[:,2] # Retrieve Col

array([ 4,  5, 13])

In [33]:
ar =2*np.arange(6)
ar

array([ 0,  2,  4,  6,  8, 10])

In [34]:
ar[1:6:2]

array([ 2,  6, 10])

In [35]:
 ar[:4] # obtain first n element

array([0, 2, 4, 6])

In [36]:
ar[4:] # Start at n until end

array([ 8, 10])

In [37]:
ar[::2] #Slice array with step value

array([0, 4, 8])

### Array Masking or Simply Select or Filter Out Elements

In [38]:
np.random.seed(10)

ar =np.random.random_integers(0,25,10)
OddMask = ~(ar%2 ==0)
evenMask = (ar%2 ==0)
print(ar)
print((ar[OddMask],ar[evenMask]))


[ 9  4 15  0 17 25 16 17  8  9]
(array([ 9, 15, 17, 25, 17,  9]), array([ 4,  0, 16,  8]))


C:\Users\Dell\AppData\Local\Temp/ipykernel_1160/1055730347.py:3: DeprecationWarning: This function is deprecated. Please call randint(0, 25 + 1) instead
  ar =np.random.random_integers(0,25,10)


In [39]:
ar = np.array(["Hungary","Nigeria","India","Sri Lanka","United Kingdom", " ","China"])
ar[ar==' ']='USA'
ar[[1,3,5]] ='Country Changed'
ar
               

array(['Hungary', 'Country Change', 'India', 'Country Change',
       'United Kingdom', 'Country Change', 'China'], dtype='<U14')

### Complex Indexing

In [40]:
ar =np.arange(15)
ar

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [41]:
ar2 =np.arange(0,-10,-1)[::-1]
ar2

array([-9, -8, -7, -6, -5, -4, -3, -2, -1,  0])

In [42]:
ar[:10]=ar2
ar


array([-9, -8, -7, -6, -5, -4, -3, -2, -1,  0, 10, 11, 12, 13, 14])

## Basic Operations

In [43]:
ar = np.arange(0,7)*5
ar

array([ 0,  5, 10, 15, 20, 25, 30])

In [44]:
ar = np.arange(5)**4
ar

array([  0,   1,  16,  81, 256], dtype=int32)

In [45]:
ar**0.5

array([ 0.,  1.,  4.,  9., 16.])

In [46]:
ar = 3+np.arange(0,30,3)
ar

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [47]:
ar1 = np.arange(1,11)
ar1


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [48]:
ar - ar1

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [49]:
ar/ar1

array([3., 3., 3., 3., 3., 3., 3., 3., 3., 3.])

In [50]:
ar*ar1

array([  3,  12,  27,  48,  75, 108, 147, 192, 243, 300])

In [13]:
ar = np.arange(1000)
ar1 = range(1000)
%timeit [ar1[i]**3 for i in ar1]


330 µs ± 1.64 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [15]:
%timeit ar**3

2.65 µs ± 8.58 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


## Matrix Multiplication

In [17]:
ar = np.array([[1,1],[1,1]])
ar

array([[1, 1],
       [1, 1]])

In [19]:
ar1 = np.array([[2,2],[2,2]])
ar1



array([[2, 2],
       [2, 2]])

In [21]:
ar.dot(ar1)

array([[4, 4],
       [4, 4]])

## Element wise Logical comparision

In [23]:
arr =np.arange(1,5)
arr

array([1, 2, 3, 4])

In [27]:
ar2 = np.arange(5,1,-1)
ar2


array([5, 4, 3, 2])

In [31]:
arr < ar2

array([ True,  True, False, False])

#### Logical function


In [36]:
l1 = np.array([True, False,True,False])
l2 =np.array([False, False, True, True])
np.logical_and(l1,l2)

array([False, False,  True, False])

In [38]:
np.logical_or(l1,l2)

array([ True, False,  True,  True])

In [41]:
np.logical_not(l1)

array([False,  True, False,  True])

In [46]:
np.sin([np.pi, np.pi/2])

array([1.2246468e-16, 1.0000000e+00])

In [48]:
ar.T

array([[1, 1],
       [1, 1]])

In [50]:
np.all(l1==l2)

False

### Reduction Operations

In [5]:
ar = np.arange(1,6)
ar= np.tile([ar],(2,1))
print(ar)
np.prod(ar,axis=0) ## axis =0 means column wise 1 mean rowise


[[1 2 3 4 5]
 [1 2 3 4 5]]


array([ 1,  4,  9, 16, 25])

In [83]:
ar.sum()

30

In [84]:
ar.mean()

3.0

In [6]:
np.median(ar)

3.0

In [11]:
ar.T # Transpose

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4],
       [5, 5]])

In [13]:
np.array_equal(ar,ar)


True

### Statistical Operators

In [18]:
np.random.seed(10)
ar = np.random.randint(0,10,size=(4,5))
ar

array([[9, 4, 0, 1, 9],
       [0, 1, 8, 9, 0],
       [8, 6, 4, 3, 0],
       [4, 6, 8, 1, 8]])

In [24]:
ar.mean( axis =0) # mean of col

array([5.25, 4.25, 5.  , 3.5 , 4.25])

In [27]:
ar.std(axis =0)

array([3.56195171, 2.04633819, 3.31662479, 3.27871926, 4.26468053])

In [30]:
ar.var(axis =1)


array([14.64, 16.24,  7.36,  7.04])

In [33]:
ar.cumsum(axis =0)

array([[ 9,  4,  0,  1,  9],
       [ 9,  5,  8, 10,  9],
       [17, 11, 12, 13,  9],
       [21, 17, 20, 14, 17]], dtype=int32)

### Logical Operator

In [43]:
print(ar%7,'\n\n', ar)

np.any((ar%7)==0)

[[2 4 0 1 2]
 [0 1 1 2 0]
 [1 6 4 3 0]
 [4 6 1 1 1]] 

 [[9 4 0 1 9]
 [0 1 8 9 0]
 [8 6 4 3 0]
 [4 6 8 1 8]]


True

In [46]:
np.all(ar<11)

True

## Array Shape Manipulation

### Flattning an array

In [50]:
print(ar)
ar.ravel()

[[9 4 0 1 9]
 [0 1 8 9 0]
 [8 6 4 3 0]
 [4 6 8 1 8]]


array([9, 4, 0, 1, 9, 0, 1, 8, 9, 0, 8, 6, 4, 3, 0, 4, 6, 8, 1, 8])

In [52]:
ar.T.ravel()

array([9, 0, 8, 4, 4, 1, 6, 6, 0, 8, 4, 8, 1, 9, 3, 1, 9, 0, 0, 8])

### Reshaping or unflatten an array

In [57]:

ar1 = ar.T.ravel().copy()
ar1.reshape(5,4)



array([[9, 0, 8, 4],
       [4, 1, 6, 6],
       [0, 8, 4, 8],
       [1, 9, 3, 1],
       [9, 0, 0, 8]])

### Resizing

In [68]:
ar = np.arange(5)
ar.resize((3,3))
ar

array([[0, 1, 2],
       [3, 4, 0],
       [0, 0, 0]])

### Adding a dimension

In [79]:
ar = np.array([14,15,16]);
ar.shape


(3,)

In [80]:
ar =ar[:,np.newaxis]
ar


array([[14],
       [15],
       [16]])

## Array Sorting

In [100]:
ar = np.array([[3,2],[10,-1]])
ar

array([[ 3,  2],
       [10, -1]])

In [94]:
ar.sort(axis =0)
ar

array([[ 3, -1],
       [10,  2]])

In [97]:
ar.sort(axis =1)
ar

array([[ 2,  3],
       [-1, 10]])

In [101]:
ar.argmin(),ar.argmax()

(3, 2)